### ISSUE TITLE
Add support for progress bar

### ISSUE THREAD

**Issue by NinjaShuriken** [i2002/RainmeterMediaPlayer#6] opened 2024-03-11 12:08 UTC
Is it possible to add support for Progress Bar with Windows Media integration.

**Comment by i2002** [comment] 2024-03-11 20:17
Hi,
The plugin has progress bar for applications that support it (for example Spotify).
In which application do you have issues?

**Comment by NinjaShuriken** [comment] 2024-03-13 10:18
Hi,
Currently I tried using YouTube in a browser, the YouTubeMusic Desktop App and MusicBee

**Comment by i2002** [comment] 2024-03-13 20:25
![image](https://github.com/i2002/RainmeterMediaPlayer/assets/36770606/66bce221-2c84-4433-a3da-23076f185358)
What browser are you using? For me it works in Chrome and Firefox.

Or maybe I didn't understand your issue? You are referring to the blue progress indicator, right?

**Comment by NinjaShuriken** [comment] 2024-03-14 08:12
Indeed it does work on the browser, it was the skin I was using which did not work. Very sorry about that. I assume it not working with MusicBee and and the YouTube Music App is an issue with those respective apps then?

**Comment by i2002** [comment] 2024-03-15 19:31
I don't know which is the YouTube Music App (if you're referring to the website, it should work like normal YT).

I've just checked with MusicBee and it seems it doesn't support the windows API so it can't work with this plugin.

You can find out if the music app should work with the api or not if you look at the volume change popup in Win 10 (you can see the screenshot in the repo readme): if it shows the data from the player it should also work with the rainmeter plugin, otherwise the problem is on the music app side. (In windows 11 I believe the music player information is shown in the notifications tray instead).

As this isn't an issue with the plugin I'm gonna close this.

**Closed as completed by i2002** 2024-03-15 19:31 UTC
